; Bookmark prototype firmware
; Target: Waveshare ESP32-S3-Touch-LCD-1.28 (round 240x240 GC9A01 + CST816S touch)

[env:bookmark]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.1
    lovyan03/LovyanGFX@^1.1.16
